name: ✨ Feature Request
description: Suggest a new feature or improvement.
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: textarea
    id: background
    attributes:
      label: "💡 Background"
      placeholder: "Why is this feature needed? Describe the problem you are trying to solve."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "🧩 Proposal"
      placeholder: "Describe the feature you would like to see added."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "🚀 Expected Behavior"
      placeholder: "Describe the expected behavior or outcomes."
  - type: checkboxes
    id: platforms
    attributes:
      label: "📱 Target Platform"
      options:
        - label: "Android"
        - label: "iOS"
        - label: "Common (Shared)"
  - type: dropdown
    id: module
    attributes:
      label: "💻 Target Module"
      multiple: true
      options:
        - "firebase-common"
        - "firebase-auth"
        - "firebase-firestore"
        - "firebase-database"
        - "firebase-storage"
        - "firebase-messaging"
        - "firebase-crashlytics"
        - "firebase-config"
        - "firebase-functions"
        - "firebase-perf"
        - "firebase-inappmessaging"
        - "firebase-appcheck"
        - "firebase-appdistribution"
        - "firebase-dataconnect"
        - "firebase-installations"
        - "firebase-abt"
        - "firebase-ai"
        - "encoders"
        - "transport"
        - "example (Sample App)"
    validations:
      required: true
