package zone.ien.firebase.encoders.protoc

import com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import java.io.InputStream
import java.io.OutputStream

public fun main() {
    val request = CodeGeneratorRequest.parseFrom(System.`in`)
    val response = generate(request)
    response.writeTo(System.out)
}

public fun generate(request: CodeGeneratorRequest): CodeGeneratorResponse {
    val responseBuilder = CodeGeneratorResponse.newBuilder()

    for (fileProto in request.protoFileList) {
        // Skip proto files that are not explicitly requested to be generated
        if (!request.fileToGenerateList.contains(fileProto.name)) continue

        val packageName = if (fileProto.hasOptions() && fileProto.options.hasJavaPackage()) {
            fileProto.options.javaPackage
        } else {
            fileProto.`package`
        }

        for (messageType in fileProto.messageTypeList) {
            val className = messageType.name
            val encoderName = "${className}Encoder"

            val sb = StringBuilder()
            sb.append("// Generated by protoc-gen-firebase-encoders. Do not edit.\n")
            if (packageName.isNotEmpty()) {
                sb.append("package $packageName\n\n")
            }

            sb.append("import zone.ien.firebase.encoders.FieldDescriptor\n")
            sb.append("import zone.ien.firebase.encoders.ObjectEncoder\n")
            sb.append("import zone.ien.firebase.encoders.ObjectEncoderContext\n")
            sb.append("import zone.ien.firebase.encoders.proto.Protobuf\n")
            sb.append("import zone.ien.firebase.encoders.proto.IntEncoding\n\n")

            sb.append("public class $encoderName : ObjectEncoder<$className> {\n")
            sb.append("    public companion object {\n")
            sb.append("        public val INSTANCE: $encoderName = $encoderName()\n")
            sb.append("    }\n\n")

            // Build static descriptors with tag parameters
            for (field in messageType.fieldList) {
                val fieldName = field.name
                val camelName = NamingHelper.toCamelCase(fieldName)
                val descriptorValName = "${camelName}Descriptor"
                val tag = field.number

                sb.append("    private val $descriptorValName = FieldDescriptor.builder(\"$camelName\")\n")
                sb.append("        .withProperty(Protobuf(tag = $tag, intEncoding = IntEncoding.DEFAULT))\n")
                sb.append("        .build()\n\n")
            }

            sb.append("    override fun encode(value: $className, context: ObjectEncoderContext) {\n")
            for (field in messageType.fieldList) {
                val fieldName = field.name
                val camelName = NamingHelper.toCamelCase(fieldName)
                val descriptorValName = "${camelName}Descriptor"
                sb.append("        context.add($descriptorValName, value.$camelName)\n")
            }
            sb.append("    }\n")
            sb.append("}\n")

            val outputFileName = if (packageName.isNotEmpty()) {
                packageName.replace('.', '/') + "/" + encoderName + ".kt"
            } else {
                encoderName + ".kt"
            }

            val responseFile = CodeGeneratorResponse.File.newBuilder()
                .setName(outputFileName)
                .setContent(sb.toString())
                .build()

            responseBuilder.addFile(responseFile)
        }
    }

    return responseBuilder.build()
}
