package zone.ien.firebase.encoders.protoc

import com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import java.io.InputStream
import java.io.OutputStream

public fun main() {
    val request = CodeGeneratorRequest.parseFrom(System.`in`)
    val response = generate(request)
    response.writeTo(System.out)
}

public fun generate(request: CodeGeneratorRequest): CodeGeneratorResponse {
    val responseBuilder = CodeGeneratorResponse.newBuilder()

    for (fileProto in request.protoFileList) {
        // Skip proto files that are not explicitly requested to be generated
        if (!request.fileToGenerateList.contains(fileProto.name)) continue

        val packageName = if (fileProto.hasOptions() && fileProto.options.hasJavaPackage()) {
            fileProto.options.javaPackage
        } else {
            fileProto.`package`
        }

        val allMessages = collectMessageTypes(fileProto.messageTypeList)
        for ((fullName, messageType) in allMessages) {
            val className = fullName
            val encoderName = "${fullName.replace('.', '_')}Encoder"

            val sb = StringBuilder()
            sb.append("// Generated by protoc-gen-firebase-encoders. Do not edit.\n")
            if (packageName.isNotEmpty()) {
                sb.append("package $packageName\n\n")
            }

            sb.append("import zone.ien.firebase.encoders.FieldDescriptor\n")
            sb.append("import zone.ien.firebase.encoders.ObjectEncoder\n")
            sb.append("import zone.ien.firebase.encoders.ObjectEncoderContext\n")
            sb.append("import zone.ien.firebase.encoders.proto.Protobuf\n")
            sb.append("import zone.ien.firebase.encoders.proto.IntEncoding\n\n")

            sb.append("public class $encoderName : ObjectEncoder<$className> {\n")
            sb.append("    public companion object {\n")
            sb.append("        public val INSTANCE: $encoderName = $encoderName()\n")
            sb.append("    }\n\n")

            // Build static descriptors with tag parameters
            for (field in messageType.fieldList) {
                val fieldName = field.name
                val camelName = NamingHelper.toCamelCase(fieldName)
                val descriptorValName = "${camelName}Descriptor"
                val tag = field.number

                sb.append("    private val $descriptorValName = FieldDescriptor.builder(\"$camelName\")\n")
                sb.append("        .withProperty(Protobuf(tag = $tag, intEncoding = IntEncoding.DEFAULT))\n")
                sb.append("        .build()\n\n")
            }

            sb.append("    override fun encode(value: $className, context: ObjectEncoderContext) {\n")
            for (field in messageType.fieldList) {
                val fieldName = field.name
                val camelName = NamingHelper.toCamelCase(fieldName)
                val descriptorValName = "${camelName}Descriptor"

                val isRepeated = field.label == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Label.LABEL_REPEATED
                val isMap = isRepeated && field.type == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE && field.typeName.endsWith("Entry")

                val propertyName = when {
                    isMap -> "${camelName}Map"
                    isRepeated -> "${camelName}List"
                    else -> camelName
                }

                sb.append("        context.add($descriptorValName, value.$propertyName)\n")
            }
            sb.append("    }\n")
            sb.append("}\n")

            val outputFileName = if (packageName.isNotEmpty()) {
                packageName.replace('.', '/') + "/" + encoderName + ".kt"
            } else {
                encoderName + ".kt"
            }

            val responseFile = CodeGeneratorResponse.File.newBuilder()
                .setName(outputFileName)
                .setContent(sb.toString())
                .build()

            responseBuilder.addFile(responseFile)
        }
    }

    return responseBuilder.build()
}

private fun collectMessageTypes(
    messageTypes: List<com.google.protobuf.DescriptorProtos.DescriptorProto>,
    parentNamePrefix: String = ""
): List<Pair<String, com.google.protobuf.DescriptorProtos.DescriptorProto>> {
    val list = mutableListOf<Pair<String, com.google.protobuf.DescriptorProtos.DescriptorProto>>()
    for (messageType in messageTypes) {
        val fullName = if (parentNamePrefix.isEmpty()) messageType.name else "$parentNamePrefix.${messageType.name}"
        list.add(fullName to messageType)
        list.addAll(collectMessageTypes(messageType.nestedTypeList, fullName))
    }
    return list
}
